name: Container Image CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the container image
        run: docker build . --file Dockerfile --tag localbuild/testimage1:latest
      - uses: anchore/scan-action@v3
        with:
          image: "localbuild/testimage:latest"
          fail-build: true
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: naveenr211
          password: c68671f2-540c-400e-a17a-d2bb6305a5a9
      -
        name: Build and Push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: naveenr211/anchor-jenkins:testimage
